### PR TITLE
Refactor and dockerize

### PR DESCRIPTION
**Pull request by idleherb**
- break down main program into functions
- simplify fx workflow
- add Dockerfile for OS independent execution

### CODE REVIEW

**Review by tangowithfoxtrot — APPROVED** [review]
You really cleaned it up. Thanks.

**Comment by idleherb** [comment]
@trevorftard do you want to merge it? I don't have the permissions to do it. Next step would be to add a simple web server with a frontend and deploy this on something like heroku.

**Comment by tangowithfoxtrot** [comment]
I actually have no idea how to work with github. I'd be willing to, but I
need someone to hold my hand to merge it I guess.

**Comment by idleherb** [comment]
Well you just press the green merge button ;) Github does the rest...

**Pull request merged**
